// scripts/seed-firebase.ts
// Complete multilingual azkar data with Indonesian support
// AUTO-GENERATED by merge_azkar.py
// Generated: merge_azkar.py
// Total entries: 25

import { collection, doc, setDoc } from "firebase/firestore";
import { db } from "../config/firebase";

interface HadithReference {
  bookId: string;
  number: number;
  volume?: number;
}

interface ZikrData {
  id: string;
  arabic: string;
  translations: {
    [languageCode: string]: string;
  };
  transliteration?: {
    [languageCode: string]: string;
  };
  benefits: {
    [languageCode: string]: string;
  };
  repetitions: number;
  category: "morning" | "evening" | "both";
  order: number;
  references: HadithReference[];
}

const azkarData: ZikrData[] = [
    {
    id: "ayatul_kursi",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    translations: {
      en: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.",
      ur: "اللہ کے سوا کوئی معبود نہیں، وہ زندہ اور قائم رہنے والا ہے، اُسے نہ اونگھ آتی ہے نہ نیند، آسمانوں اور زمین میں جو کچھ ہے سب اُسی کا ہے، کون ہے جو اس کی اجازت کے بغیر اس کے پاس سفارش کرسکے، وہ جانتا ہے جو ان کے آگے اور پیچھے ہے، اور وہ اس کے علم میں سے کسی چیز کا احاطہ نہیں کرسکتے مگر جتنا وہ چاہے، اس کی کرسی آسمانوں اور زمین کو محیط ہے، اور ان دونوں کی حفاظت اسے نہیں تھکاتی، اور وہ بلند و بالا اور عظیم ہے",
      bn: "আল্লাহ ছাড়া কোন উপাস্য নেই, তিনি চিরঞ্জীব, সবকিছুর ধারক। তাঁকে তন্দ্রা ও নিদ্রা স্পর্শ করে না। আসমান ও জমিনে যা কিছু রয়েছে, সব তাঁরই। কে আছে এমন যে সুপারিশ করবে তাঁর কাছে তাঁর অনুমতি ছাড়া? তিনি জানেন যা তাদের সামনে আছে এবং যা তাদের পিছনে আছে। তাঁর জ্ঞানের কোন কিছুকেই তারা পরিবেষ্টিত করতে পারে না, কিন্তু যতটুকু তিনি ইচ্ছা করেন। তাঁর কুরসী সমস্ত আসমান ও জমিনকে পরিবেষ্টিত করে আছে। আর সেগুলোর রক্ষণাবেক্ষণ তাঁকে ক্লান্ত করে না। তিনিই সর্বোচ্চ এবং সর্বমহান।",
      hi: "अल्लाह के सिवा कोई माबूद नहीं, वह जिंदा और कायम है, उसे न ऊंघ आती है न नींद, आसमानों और जमीन में जो कुछ है सब उसी का है, कौन है जो उसकी इजाजत के बगैर उसके पास सिफारिश कर सके, वह जानता है जो उनके आगे और पीछे है, और वह उसके इल्म में से किसी चीज का अहाता नहीं कर सकते मगर जितना वह चाहे, उसकी कुर्सी आसमानों और जमीन को मुहीत है, और उन दोनों की हिफाजत उसे नहीं थकाती, और वह बुलंद व बाला और अजीम है",
      id: "Allah, tidak ada Tuhan yang berhak disembah melainkan Dia Yang Hidup kekal lagi terus menerus mengurus (makhluk-Nya); tidak mengantuk dan tidak tidur. Kepunyaan-Nya apa yang di langit dan di bumi. Siapakah yang dapat memberi syafa'at di sisi Allah tanpa izin-Nya? Allah mengetahui apa-apa yang di hadapan mereka dan di belakang mereka, dan mereka tidak mengetahui apa-apa dari ilmu Allah melainkan apa yang dikehendaki-Nya. Kursi Allah meliputi langit dan bumi. Dan Allah tidak merasa berat memelihara keduanya, dan Allah Maha Tinggi lagi Maha Besar."
    },
    transliteration: {
      en: "Allahu la ilaha illa Huwal Hayyul Qayyum la ta'khudhuhu sinatun wa la nawm lahu ma fis samawati wa ma fil ard man dhal ladhi yashfa'u 'indahu illa bi'idhnih ya'lamu ma bayna aydihim wa ma khalfahum wa la yuhituna bishay'im min 'ilmihi illa bima sha'a wasi'a kursiyyuhus samawati wal ard wa la ya'uduhu hifdhuhuma wa Huwal 'Aliyyul 'Adhim",
      ur: "اللہ لا الہ الا ھو الحی القیوم لا تاخذہ سنۃ ولا نوم لہ ما فی السماوات وما فی الارض من ذا الذی یشفع عندہ الا باذنہ یعلم ما بین ایدیھم وما خلفھم ولا یحیطون بشیء من علمہ الا بما شاء وسع کرسیہ السماوات والارض ولا یؤدہ حفظھما وھو العلی العظیم",
      bn: "আল্লাহু লা ইলাহা ইল্লা হুওয়াল হাইয়ুল কাইয়ূম লা তা'খুযুহু সিনাতুন ওয়া লা নাউম লাহু মা ফিস সামাওয়াতি ওয়া মা ফিল আরদ মান যাল্লাযী ইয়াশফা'উ ইন্দাহু ইল্লা বিইযনিহ ইয়া'লামু মা বাইনা আইদীহিম ওয়া মা খালফাহুম ওয়া লা ইউহীতূনা বিশাইয়িম মিন ইলমিহী ইল্লা বিমা শাআ ওয়াসি'আ কুরসিয়্যুহুস সামাওয়াতি ওয়াল আরদ ওয়া লা ইয়াঊদুহু হিফযুহুমা ওয়া হুওয়াল আলিয়্যুল আযীম",
      hi: "अल्लाहु ला इलाहा इल्ला हुवल हय्युल कय्यूम ला ताखुजुहु सिनतुन वला नौम लहु मा फिस्समावाति वमा फिल अर्ज़ मन जल्लजी यशफउ इन्दहु इल्ला बिइज्निह यालमु मा बैना ऐदीहिम वमा खल्फहुम वला युहीतूना बिशैइम मिन इल्मिही इल्ला बिमा शाअ वसिअ कुर्सिय्युहुस्समावाति वल अर्ज़ वला यऊदुहु हिफ्जुहुमा व हुवल अलिय्युल अजीम",
      id: "Allahu laa ilaaha illaa huwal hayyul qayyuum, laa ta'khudzuhuu sinatuw wa laa nauum, lahuu maa fissamaawaati wa maa fil ardh, man dzal ladzii yasyfa'u 'indahuu illaa bi idznih, ya'lamu maa baina aidiihim wa maa khalfahum, wa laa yuhiithuuna bi syai'im min 'ilmihii illaa bimaa syaa', wasi'a kursiyyuhus samaawaati wal ardh, wa laa ya'uuduhuu hifzhuhumaa, wa huwal 'aliyyul 'azhiim"
    },
    benefits: {
      en: "He who recites Ayat al-Kursi becomes safe from Shaitan and Jinn and a guard is appointed for his safety",
      ur: "آیۃ الکرسی پڑھنے سے شیطان اور جنات سے محفوظ رہتے ہیں، جنت کے سوا کوئی چیز نہیں روکتی",
      bn: "যে ব্যক্তি আয়াতুল কুরসী পাঠ করে সে শয়তান ও জিন থেকে নিরাপদ থাকে এবং তার নিরাপত্তার জন্য একজন প্রহরী নিযুক্ত করা হয়",
      hi: "आयातुल कुर्सी पढ़ने वाला शैतान और जिन्नात से महफूज़ हो जाता है और उसकी हिफाज़त के लिये एक मुहाफिज़ मुकर्रर कर दिया जाता है",
      id: "Barangsiapa yang membaca Ayat Kursi akan terlindung dari setan dan jin, dan tidak ada yang menghalanginya masuk surga"
    },
    repetitions: 1,
    category: "both",
    order: 1,
    references: [
      { bookId: "bukhari", number: 2311 },
      { bookId: "nasai_kubra", number: 8017 },
      { bookId: "mustadrak", number: 2064 }
    ]
  },
  {
    id: "surah_ikhlas",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    translations: {
      en: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent.",
      ur: "کہو: وہ اللہ ایک ہے، اللہ بے نیاز ہے، نہ اس کی کوئی اولاد ہے نہ وہ کسی کی اولاد ہے، اور کوئی اس کا ہمسر نہیں",
      bn: "বলুন: তিনি আল্লাহ, এক। আল্লাহ অমুখাপেক্ষী। তিনি কাউকে জন্ম দেননি এবং কেউ তাকে জন্ম দেয়নি। এবং তাঁর সমতুল্য কেউ নেই।",
      hi: "कहो: वह अल्लाह एक है, अल्लाह बेनियाज़ है, न उसकी कोई औलाद है न वह किसी की औलाद है, और कोई उसका हमसर नहीं",
      id: "Katakanlah: Dia-lah Allah, Yang Maha Esa. Allah adalah Tuhan yang bergantung kepada-Nya segala sesuatu. Dia tiada beranak dan tidak pula diperanakkan, dan tidak ada seorangpun yang setara dengan Dia."
    },
    transliteration: {
      en: "Qul Huwa Allahu Ahad Allahus Samad Lam yalid wa lam yulad Wa lam yakun lahu kufuwan ahad",
      ur: "قل ھو اللہ احد، اللہ الصمد، لم یلد ولم یولد، ولم یکن لہ کفوا احد",
      bn: "কুল হুওয়াল্লাহু আহাদ আল্লাহুস সামাদ লাম ইয়ালিদ ওয়া লাম ইউলাদ ওয়া লাম ইয়াকুন লাহু কুফুওয়ান আহাদ",
      hi: "कुल हुवल्लाहु अहद अल्लाहुस्समद लम यलिद व लम यूलद व लम यकुन लहु कुफुवन अहद",
      id: "Qul huwallahu ahad, Allahush shamad, Lam yalid wa lam yuulad, Wa lam yakul lahuu kufuwan ahad"
    },
    benefits: {
      en: "The recitation of Muawwidhat will suffice you against everything (against Jinn and magic)",
      ur: "معوذات کی تلاوت (جنات اور جادو کے خلاف) ہر شے سے کافی ہو جاتی ہے",
      bn: "মুআওবিযাত পাঠ (জিন ও জাদুর বিরুদ্ধে) সব কিছু থেকে যথেষ্ট",
      hi: "मुअव्विज़ात की तिलावत (जिन्नात और जादू के खिलाफ़) हर शै से काफ़ी हो जाती है",
      id: "Membaca Muawwidhat (Al-Ikhlas, Al-Falaq, An-Nas) akan melindungi dari segala hal termasuk jin dan sihir"
    },
    repetitions: 3,
    category: "both",
    order: 2,
    references: [
      { bookId: "tirmidhi", number: 3575 },
      { bookId: "abu_dawud", number: 5082 }
    ]
  },
  {
    id: "surah_falaq",
    arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
    translations: {
      en: "Say: I seek refuge in the Lord of daybreak, From the evil of that which He created, And from the evil of darkness when it settles, And from the evil of the blowers in knots, And from the evil of an envier when he envies.",
      ur: "کہو: میں صبح کے رب کی پناہ مانگتا ہوں، ہر مخلوق کے شر سے، اندھیری رات کے شر سے جب وہ چھا جائے، گرہوں میں پھونکنے والیوں کے شر سے، اور حاسد کے شر سے جب وہ حسد کرے",
      bn: "বলুন: আমি আশ্রয় প্রার্থনা করছি ঊষার পালনকর্তার, তিনি যা সৃষ্টি করেছেন তার অনিষ্ট থেকে, অন্ধকার রাত্রির অনিষ্ট থেকে যখন তা সমাগত হয়, গ্রন্থিতে ফুৎকার দিয়ে জাদুকারিণীদের অনিষ্ট থেকে, এবং হিংসুকের অনিষ্ট থেকে যখন সে হিংসা করে।",
      hi: "कहो: मैं सुबह के रब की पनाह मांगता हूं, हर मखलूक के शर से, अंधेरी रात के शर से जब वह छा जाए, गिरहों में फूंकने वालियों के शर से, और हासिद के शर से जब वह हसद करे",
      id: "Katakanlah: Aku berlindung kepada Tuhan Yang Menguasai waktu subuh, dari kejahatan apa yang Dia ciptakan, dan dari kejahatan malam apabila telah gelap gulita, dan dari kejahatan wanita-wanita tukang sihir yang menghembus pada buhul-buhul, dan dari kejahatan pendengki bila ia dengki."
    },
    transliteration: {
      en: "Qul a'udhu bi Rabbil falaq Min sharri ma khalaq Wa min sharri ghasiqin idha waqab Wa min sharrin naffathati fil 'uqad Wa min sharri hasidin idha hasad",
      ur: "قل اعوذ برب الفلق، من شر ما خلق، ومن شر غاسق اذا وقب، ومن شر النفاثات فی العقد، ومن شر حاسد اذا حسد",
      bn: "কুল আউযু বিরাব্বিল ফালাক মিন শাররি মা খালাক ওয়া মিন শাররি গাসিকিন ইযা ওয়াকাব ওয়া মিন শাররিন নাফফাসাতি ফিল উকাদ ওয়া মিন শাররি হাসিদিন ইযা হাসাদ",
      hi: "कुल अऊज़ु बिरब्बिल फ़लक़ मिन शर्रि मा ख़लक़ व मिन शर्रि गासिक़िन इज़ा वक़ब व मिन शर्रिन नफ़्फ़ासाति फ़िल उक़द व मिन शर्रि हासिदिन इज़ा हसद",
      id: "Qul a'uudzu birabbil falaq, Min syarri maa khalaq, Wa min syarri ghaasiqin idzaa waqab, Wa min syarrin naffaatsaati fil 'uqad, Wa min syarri haasidin idzaa hasad"
    },
    benefits: {
      en: "The recitation of Muawwidhat will suffice you against everything (against Jinn and magic)",
      ur: "معوذات کی تلاوت (جنات اور جادو کے خلاف) ہر شے سے کافی ہو جاتی ہے",
      bn: "মুআওবিযাত পাঠ (জিন ও জাদুর বিরুদ্ধে) সব কিছু থেকে যথেষ্ট",
      hi: "मुअव्विज़ात की तिलावत (जिन्नात और जादू के खिलाफ़) हर शै से काफ़ी हो जाती है",
      id: "Membaca Muawwidhat akan melindungi dari segala hal termasuk jin dan sihir"
    },
    repetitions: 3,
    category: "both",
    order: 3,
    references: [
      { bookId: "tirmidhi", number: 3575 },
      { bookId: "abu_dawud", number: 5082 }
    ]
  },
  {
    id: "surah_nas",
    arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ",
    translations: {
      en: "Say: I seek refuge in the Lord of mankind, The King of mankind, The God of mankind, From the evil of the whisperer who withdraws, Who whispers in the breasts of mankind, Among jinn and among men.",
      ur: "کہو: میں لوگوں کے رب کی، لوگوں کے بادشاہ کی، لوگوں کے معبود کی پناہ مانگتا ہوں، وسوسہ ڈالنے والے کے شر سے جو پیچھے ہٹ جاتا ہے، جو لوگوں کے دلوں میں وسوسے ڈالتا ہے، جنوں اور انسانوں میں سے",
      bn: "বলুন: আমি আশ্রয় প্রার্থনা করছি মানুষের পালনকর্তার, মানুষের অধিপতির, মানুষের উপাস্যের, তার অনিষ্ট থেকে যে কুমন্ত্রণা দেয় ও আত্মগোপন করে, যে কুমন্ত্রণা দেয় মানুষের অন্তরে, জিনের মধ্য থেকে এবং মানুষের মধ্য থেকে।",
      hi: "कहो: मैं लोगों के रब की, लोगों के बादशाह की, लोगों के माबूद की पनाह मांगता हूं, वसवसा डालने वाले के शर से जो पीछे हट जाता है, जो लोगों के दिलों में वसवसे डालता है, जिन्नों और इंसानों में से",
      id: "Katakanlah: Aku berlindung kepada Tuhan (yang memelihara dan menguasai) manusia. Raja manusia. Sembahan manusia. Dari kejahatan (bisikan) syaitan yang biasa bersembunyi, yang membisikkan (kejahatan) ke dalam dada manusia, dari (golongan) jin dan manusia."
    },
    transliteration: {
      en: "Qul a'udhu bi Rabbin nas Malikin nas Ilahin nas Min sharril waswasil khannas Alladhi yuwaswisu fi sudurin nas Minal jinnati wan nas",
      ur: "قل اعوذ برب الناس، ملک الناس، الہ الناس، من شر الوسواس الخناس، الذی یوسوس فی صدور الناس، من الجنۃ والناس",
      bn: "কুল আউযু বিরাব্বিন নাস মালিকিন নাস ইলাহিন নাস মিন শাররিল ওয়াসওয়াসিল খান্নাস আল্লাযী ইউওয়াসউইসু ফী সুদূরিন নাস মিনাল জিন্নাতি ওয়ান নাস",
      hi: "कुल अऊज़ु बिरब্বিन नास मलिकिन नास इलाहिन নাস মিন शर्रिল वसवासिल खन्नास अल्लज़ी युवसविसु फ़ी सुदूरिন नास मिनल जिন्नति वन नास",
      id: "Qul a'uudzu birabbin naas, Malikin naas, Ilaahin naas, Min syarril waswaasil khannaas, Alladzii yuwaswisu fii shuduurin naas, Minal jinnati wan naas"
    },
    benefits: {
      en: "The recitation of Muawwidhat will suffice you against everything (against Jinn and magic)",
      ur: "معوذات کی تلاوت (جنات اور جادو کے خلاف) ہر شے سے کافی ہو جاتی ہے",
      bn: "মুআওবিযাত পাঠ (জিন ও জাদুর বিরুদ্ধে) সব কিছু থেকে যথেষ্ট",
      hi: "मुअव्विज़ात की तिलावत (जिन्नात और जादू के खिलाफ़) हर शै से काफ़ी हो जाती है",
      id: "Membaca Muawwidhat akan melindungi dari segala hal termasuk jin dan sihir"
    },
    repetitions: 3,
    category: "both",
    order: 4,
    references: [
      { bookId: "tirmidhi", number: 3575 },
      { bookId: "abu_dawud", number: 5082 }
    ]
  },
  {
    id: "la_ilaha_illallah_10",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    translations: {
      en: "There is none worthy of worship but Allah alone with no partner or associate. He is the dominion, to Him is praise and He has power over all things.",
      ur: "نہیں کوئی معبود سوائے اللہ کے، وہ اکیلا ہے، نہیں کوئی شریک اُسکا، اُسی کی بادشاہی ہے، اور اُسی کے لیے سب تعریفیں ہیں، اور وہ ہر شے پر پوری طرح قدرت رکھتا ہے",
      bn: "নেই কোন মাবুদ মগর আল্লাহ, তিনি একা, নেই কোই শরীক তাঁর, তাঁরই রাজত্ব, এবং তাঁরই সব প্রশংসা, এবং তিনি সকল বিষয়ে সর্বশক্তিমান।",
      hi: "नहीं है कोई माबूद मगर अल्लाह, वह अकेला है, नहीं है कोई शरीक उसका, उसी की बादशाही है और उसी के लिए सब तारीफ़ है, और वह हर चीज़ पर पूरी कुदरत रखता है",
      id: "Tiada Tuhan yang berhak disembah kecuali Allah Yang Maha Esa, tiada sekutu bagi-Nya. Bagi-Nya kerajaan dan bagi-Nya segala pujian. Dan Dia Maha Kuasa atas segala sesuatu."
    },
    transliteration: {
      en: "La ilaha illallahu wahdahu la sharika lahu lahul mulku wa lahul hamdu wa Huwa 'ala kulli shay'in Qadir",
      ur: "لا الہ الا اللہ وحدہ لا شریک لہ، لہ الملک ولہ الحمد وھو علی کل شیء قدیر",
      bn: "লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারীকা লাহু লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুওয়া আলা কুল্লি শাইয়িন কাদীর",
      hi: "ला इलाहा इल्लल्लाहु वहदहु ला शरीका लहु लहुल मुल्कु व लहुल हम्दु व हुवा अला कुल्लि शैइन क़दीर",
      id: "Laa ilaaha illallahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai'in qadiir"
    },
    benefits: {
      en: "The one who recites these words gets reward of freeing 4 slaves. And he is guarded against every dangerous thing and Shaitan during the entire day and night",
      ur: "یہ کلمات پڑھنے والے کو 4 غلام آزاد کرنے کا ثواب ملتا ہے اور تمام دن رات میں ہر خطرناک چیز اور شیطان کے خلاف اسکا بچاو ہو جاتا ہے",
      bn: "যে ব্যক্তি এই কলিমাত পড়ে তাকে ৪ গোলাম আজাদ করার সওয়াব মিলবে এবং সারা দিন ও রাতে সমস্ত বিপদজনক জিনিস এবং শয়তান থেকে হেফাজত থাকবে",
      hi: "ये कलिमात पढ़ने वाले को 4 गुलाम आज़ाद करने का सवाब मिलता है और तमाम दिन रात में हर खतरनाक चीज़ और शैतान के खिलाफ़ उसका बचाव हो जाता है",
      id: "Barangsiapa yang membaca kalimat ini akan mendapat pahala membebaskan 4 budak. Dan dia akan terlindung dari segala hal berbahaya dan setan sepanjang siang dan malam"
    },
    repetitions: 10,
    category: "both",
    order: 5,
    references: [
      { bookId: "muslim", number: 6844 },
      { bookId: "abu_dawud", number: 5077 }
    ]
  },
  {
    id: "raditu_billah",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ نَبِيًّا",
    translations: {
      en: "I am pleased with Allah as my Lord, Islam as my religion, and Muhammad ﷺ as my Prophet",
      ur: "راضی ہوں میں اللہ کو رب، اور اسلام کو دین، اور محمد ﷺ کو نبی",
      bn: "আমি সন্তুষ্ট আল্লাহকে রব হিসেবে, ইসলামকে দ্বীন হিসেবে এবং মুহাম্মদ ﷺ কে নবী হিসেবে",
      hi: "राज़ी हूं मैं अल्लाह के रब होने पर, और इस्लाम के दीन होने पर, और मुहम्मद ﷺ के नबी होने पर",
      id: "Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad ﷺ sebagai Nabiku"
    },
    transliteration: {
      en: "Raditu billahi Rabba wa bil Islami dina wa bi Muhammadin nabiyya",
      ur: "رضیت باللہ ربا وبالاسلام دینا وبمحمد نبیا",
      bn: "রাদীতু বিল্লাহি রব্বা ওয়া বিল ইসলামি দীনা ওয়া বি মুহাম্মাদিন নাবিয়্যা",
      hi: "रज़ीतु बिल्लाहि रब्বन व बিल इस्लामি दीनन व बि मुहम्मदिन नबिय्यन",
      id: "Radhiitu billaahi rabba, wa bil islaami diina, wa bi muhammadin nabiyya"
    },
    benefits: {
      en: "The one who recites these words will surely get the Heaven and Allah will please him on the Day of Judgment",
      ur: "یہ کلمات پڑھنے والے پر جنّت واجب ہو جائے گی اور قیامت والے دن اللہ اسے خوش کر دے گا",
      bn: "যে ব্যক্তি এই কলিমাত পড়বে তার জন্য জান্নাত ওয়াজিব হয়ে যাবে এবং কিয়ামতের দিন আল্লাহ তাকে খুশি করবেন",
      hi: "ये कलिमात पढ़ने वाले पर जन्नत वाजिब हो जायेगी और क़यामत वाले दिन अल्लाह उसे खुश कर देंगा",
      id: "Barangsiapa yang membaca kalimat ini, surga pasti untuknya dan Allah akan meridhainya di Hari Kiamat"
    },
    repetitions: 3,
    category: "both",
    order: 6,
    references: [
      { bookId: "abu_dawud", number: 5072 },
      { bookId: "ahmad", number: 18990 }
    ]
  },
  {
    id: "bismillah_protection",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    translations: {
      en: "In the name of Allah with whose name noting on earth or in the heaven can cause harm and He is the Hearing, the Knowing",
      ur: "اللہ کے نام کے ساتھ جس کے نام میں کوئی چیز نقصان نہیں پہنچا سکتی، نہ زمین میں اور نہ آسمان میں، وہی سننے والا جاننے والا ہے",
      bn: "আল্লাহর নামে যার নামে আসমান ও জমিনে কোন কিছু ক্ষতি করতে পারে না এবং তিনি সর্বশ্রোতা, সর্বজ্ঞ",
      hi: "अल्लाह के नाम के साथ, जिसके नाम के साथ जमीन और आसमान में कोई चीज़ नुकसान नहीं पहुंचा सकती, और वही सुनने वाला जानने वाला है",
      id: "Dengan nama Allah yang dengan nama-Nya tidak ada sesuatu pun di bumi dan di langit yang dapat membahayakan, dan Dia Maha Mendengar lagi Maha Mengetahui"
    },
    transliteration: {
      en: "Bismillahil ladhi la yadurru ma'asmihi shay'un fil ardi wa la fis sama'i wa Huwas Sami'ul 'Alim",
      ur: "بسم اللہ الذی لا یضر مع اسمہ شیء فی الارض ولا فی السماء وھو السمیع العلیم",
      bn: "বিসমিল্লাহিল্লাযী লা ইয়াদুররু মা'আসমিহি শাইয়ুন ফিল আরদি ওয়া লা ফিস সামায়ি ওয়া হুওয়াস সামী'উল আলীম",
      hi: "बिस्मिल्लाहिल्लज़ी ला यज़ुर्रु मअस्मिही शैउन फ़िल अर्ज़ि वला फ़िस্समাइ व হুवस্समীउল अলীম",
      id: "Bismillahil ladzii laa yadhurru ma'asmihi syai'un fil ardhi wa laa fis samaa'i wa huwas samii'ul 'aliim"
    },
    benefits: {
      en: "Nothing can harm the person who recites these words nor will any sudden disaster reach to him",
      ur: "یہ کلمات پڑھنے والے کو نہ تو کوئی شے نقصان پہنچا سکتی ہے اور نہ ہی کোئی اچانک ناگہانی مصیبت اسے پہنچے گی",
      bn: "এই কলিমাত পড়নেওয়ালা ব্যক্তিকে কোন কিছু ক্ষতি করতে পারবে না এবং কোন আকস্মিক বিপদ তার কাছে পৌঁছবে না",
      hi: "ये कलिमात पढ़ने वाले को न तो कोई शै नुकसान पहुंचा सकती है और न ही कोई अचानक नागहानी मुसीबत उसे पहुंचेगी",
      id: "Tidak ada yang dapat membahayakan orang yang membaca kalimat ini dan tidak ada bencana mendadak yang akan menimpanya"
    },
    repetitions: 3,
    category: "both",
    order: 7,
    references: [
      { bookId: "tirmidhi", number: 3388 },
      { bookId: "abu_dawud", number: 5088 }
    ]
  },
  {
    id: "radheetu_billah",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ ﷺ نَبِيًّا",
    translations: {
      en: "I am pleased with Allah as Lord, with Islam as religion, and with Muhammad ﷺ as Prophet",
      ur: "میں اللہ کے رب ہونے پر، اسلام کے دین ہونے پر اور محمد ﷺ کے نبی ہونے پر راضی ہوں",
      bn: "আমি আল্লাহকে রব হিসেবে, ইসলামকে দ্বীন হিসেবে এবং মুহাম্মাদ ﷺ কে নবী হিসেবে সন্তুষ্ট",
      hi: "मैं अल्लाह के रब होने पर, इस्लाम के दीन होने पर और मुहम्मद ﷺ के नबी होने पर राज़ी हूं",
      id: "Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad ﷺ sebagai Nabiku"
    },
    transliteration: {
      en: "Radheetu billahi rabba, wa bil-islami deena, wa bi-Muhammadin ﷺ nabiyya",
      ur: "رضیت باللہ ربا و بالاسلام دینا و بمحمد ﷺ نبیا",
      bn: "রাদীতু বিল্লাহি রাব্বা, ওয়া বিল-ইসলামি দীনা, ওয়া বি-মুহাম্মাদিন ﷺ নাবিয়্যা",
      hi: "रज़ीतु बिल्लाहि रब्बा, व बिल-इस्लामि दीना, व बि-मुहम्मदिन ﷺ नबिय्या",
      id: "Radhiitu billaahi rabban, wa bil islaami diinan, wa bi Muhammadin ﷺ nabiyyan"
    },
    benefits: {
      en: "Jannah becomes compulsory for the one who recites this three times in the morning and evening",
      ur: "جو شخص یہ دعا صبح اور شام تین مرتبہ پڑھے اس کے لیے جنت واجب ہو جاتی ہے",
      bn: "যে ব্যক্তি সকাল ও সন্ধ্যায় তিনবার এটি পাঠ করে তার জন্য জান্নাত ওয়াজিব হয়ে যায়",
      hi: "जो शख़्स ये दुआ सुबह और शाम तीन मर्तबा पढ़े उसके लिए जन्नत वाजिब हो जाती है",
      id: "Surga menjadi wajib bagi orang yang membacanya tiga kali di pagi dan sore hari"
    },
    repetitions: 3,
    category: "both",
    order: 16,
    references: [
      { bookId: "abu_dawud", number: 1529 }
    ]
  },
  {
    id: "bismillah_tawakkaltu",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    translations: {
      en: "In the name of Allah, I place my trust in Allah, and there is neither might nor power except with Allah",
      ur: "اللہ کے نام سے، میں نے اللہ پر بھروسہ کیا، اور نہیں کوئی طاقت اور نہ قوت مگر اللہ کی مدد سے",
      bn: "আল্লাহর নামে, আমি আল্লাহর উপর ভরসা করলাম, আল্লাহর সাহায্য ছাড়া কোন শক্তি নেই",
      hi: "अल्लाह के नाम से, मैंने अल्लाह पर भरोसा किया, और नहीं कोई ताक़त और न क़ुव्वत मगर अल्लाह की मदद से",
      id: "Dengan nama Allah, aku bertawakal kepada Allah, tiada daya dan kekuatan kecuali dengan pertolongan Allah"
    },
    transliteration: {
      en: "Bismillahi tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
      ur: "بسم اللہ توکلت علی اللہ ولا حول ولا قوۃ الا باللہ",
      bn: "বিসমিল্লাহি তাওয়াক্কালতু আলাল্লাহ, ওয়া লা হাওলা ওয়া লা কুওয়াতা ইল্লা বিল্লাহ",
      hi: "बिस्मिल्लाहि तवक्कलतु अलल्लाह, व ला हौला व ला क़ुव्वता इल्ला बिल्लाह",
      id: "Bismillaahi tawakkaltu 'alallaah, wa laa haula wa laa quwwata illaa billaah"
    },
    benefits: {
      en: "Protection from going astray or being led astray, from wronging or being wronged",
      ur: "گمراہ ہونے یا کرنے سے، ظلم کرنے یا ظلم ہونے سے حفاظت",
      bn: "পথভ্রষ্ট হওয়া বা করা থেকে, জুলুম করা বা জুলুম হওয়া থেকে সুরক্ষা",
      hi: "गुमराह होने या करने से, ज़ुल्म करने या ज़ुल्म होने से हिफ़ाज़त",
      id: "Perlindungan dari tersesat atau menyesatkan, dari menzalimi atau dizalimi"
    },
    repetitions: 1,
    category: "both",
    order: 17,
    references: [
      { bookId: "abu_dawud", number: 5095 }
    ]
  },
  {
    id: "allahumma_anta_rabbi",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِن شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ لَكَ بِذَنبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنتَ",
    translations: {
      en: "O Allah! You are my Lord! None has the right to be worshipped but You. You created me and I am Your slave, and I am faithful to my covenant and my promise as much as I can. I seek refuge with You from all the evil I have done. I acknowledge before You all the blessings You have bestowed upon me, and I confess to You all my sins. So I entreat You to forgive my sins, for nobody can forgive sins except You",
      ur: "اے اللہ! تو میرا رب ہے، نہیں کوئی معبود سوائے تیرے، تو نے مجھے پیدا کیا اور میں تیرا بندہ ہوں، اور میں تیرے عہد اور وعدے پر ہوں جہاں تک میری طاقت ہے، میں تیری پناہ چاہتا ہوں اس برائی سے جو میں نے کی، میں اقرار کرتا ہوں تیری نعمت کا جو مجھ پر ہے اور اقرار کرتا ہوں اپنے گناہ کا، پس مجھے بخش دے کیونکہ گناہوں کو نہیں بخشتا مگر تو",
      bn: "হে আল্লাহ! তুমি আমার প্রতিপালক। তুমি ছাড়া কোন উপাস্য নেই। তুমি আমাকে সৃষ্টি করেছ এবং আমি তোমার বান্দা। আমি যথাসাধ্য তোমার সাথে কৃত প্রতিজ্ঞা ও অঙ্গীকারের উপর রয়েছি। আমি আমার কৃতকর্মের অনিষ্ট থেকে তোমার নিকট আশ্রয় চাই। আমি স্বীকার করছি আমার প্রতি তোমার নিয়ামত এবং স্বীকার করছি আমার পাপ। অতএব তুমি আমাকে ক্ষমা করে দাও। কারণ তুমি ছাড়া কেউ পাপ ক্ষমা করতে পারে না",
      hi: "ऐ अल्लाह! तू मेरा रब है, नहीं कोई माबूद सिवाए तेरे, तूने मुझे पैदा किया और मैं तेरा बन्दा हूं, और मैं तेरे अहद और वादे पर हूं जहां तक मेरी ताक़त है, मैं तेरी पनाह चाहता हूं उस बुराई से जो मैंने की, मैं इक़रार करता हूं तेरी नेमत का जो मुझ पर है और इक़रार करता हूं अपने गुनाह का, पस मुझे बख़्श दे क्योंकि गुनाहों को नहीं बख़्शता मगर तू",
      id: "Ya Allah, Engkau adalah Tuhanku, tiada Tuhan yang berhak disembah kecuali Engkau. Engkau telah menciptakanku dan aku adalah hamba-Mu. Aku akan setia pada perjanjianku kepada-Mu semampuku. Aku berlindung kepada-Mu dari keburukan yang telah kuperbuat. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku. Oleh karena itu, ampunilah aku. Sesungguhnya tiada yang dapat mengampuni dosa kecuali Engkau"
    },
    transliteration: {
      en: "Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayya, wa abu'u laka bidhanbi faghfir li fa'innahu la yaghfirudh-dhunuba illa ant",
      ur: "اللہم انت ربی لا الہ الا انت خلقتنی وانا عبدک وانا علی عہدک ووعدک ما استطعت اعوذ بک من شر ما صنعت ابوء لک بنعمتک علی وابوء لک بذنبی فاغفر لی فانہ لا یغفر الذنوب الا انت",
      bn: "আল্লাহুম্মা আনতা রাব্বী লা ইলাহা ইল্লা আনত, খালাকতানী ওয়া আনা আবদুক, ওয়া আনা আলা আহদিকা ওয়া ওয়া'দিকা মাসতাতা'ত, আউযু বিকা মিন শাররি মা সানা'ত, আবূউ লাকা বিনি'মাতিকা আলাইয়া, ওয়া আবূউ লাকা বিযানবী ফাগফির লী ফা'ইন্নাহু লা ইয়াগফিরুয যুনূবা ইল্লা আনত",
      hi: "अल्लाहुम्मा अन्ता रब्बी ला इलाहा इल्ला अन्त, ख़लक़तनी व अना अब्दुक, व अना अला अहदिका व वअदिका मस्ततअत, अऊज़ु बिका मिन शर्रि मा सनअत, अबूउ लका बिनिअमतिका अलय्या, व अबूउ लका बिज़म्बी फ़ग़फ़िर ली फ़इन्नहु ला यग़फ़िरुज़ ज़ुनूबा इल्ला अन्त",
      id: "Allaahumma anta rabbii laa ilaaha illaa anta, khalaqtanii wa anaa 'abduka, wa anaa 'alaa 'ahdika wa wa'dika mastatho'tu, a'uudzu bika min syarri maa shona'tu, abuu'u laka bini'matika 'alayya, wa abuu'u laka bidzanbii faghfir lii fa'innahu laa yaghfirudz dzunuuba illaa anta"
    },
    benefits: {
      en: "The master of all supplications for forgiveness. Whoever says it during the day with firm faith and dies on the same day before evening, will be from the people of Paradise",
      ur: "سید الاستغفار - تمام استغفار کی دعاؤں میں سب سے افضل۔ جو اسے دن میں یقین کے ساتھ پڑھے اور شام سے پہلے مر جائے تو وہ جنتی ہے",
      bn: "সাইয়িদুল ইস্তিগফার - সকল ক্ষমা প্রার্থনার মধ্যে সর্বশ্রেষ্ঠ। যে ব্যক্তি দিনে দৃঢ় বিশ্বাসের সাথে এটি পাঠ করে এবং সন্ধ্যার পূর্বে মারা যায়, সে জান্নাতবাসী হবে",
      hi: "सय्यिदुल इस्तिग़फ़ार - तमाम इस्तिग़फ़ार की दुआओं में सबसे अफ़ज़ल। जो इसे दिन में यक़ीन के साथ पढ़े और शाम से पहले मर जाए तो वो जन्नती है",
      id: "Sayyidul Istighfar - pemimpin segala istighfar. Barangsiapa yang membacanya di siang hari dengan keyakinan penuh dan meninggal pada hari yang sama sebelum sore, maka ia termasuk penghuni surga"
    },
    repetitions: 1,
    category: "both",
    order: 18,
    references: [
      { bookId: "bukhari", number: 6306 }
    ]
  },
  {
    id: "hasbi_allah",
    arabic: "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    translations: {
      en: "Allah is sufficient for me. There is no deity except Him. In Him I have placed my trust, and He is the Lord of the Great Throne",
      ur: "اللہ میرے لیے کافی ہے، اس کے سوا کوئی معبود نہیں، اسی پر میں نے بھروسہ کیا اور وہی عرش عظیم کا رب ہے",
      bn: "আল্লাহ আমার জন্য যথেষ্ট। তিনি ছাড়া কোন উপাস্য নেই। আমি তাঁর উপরই ভরসা করেছি। তিনি মহান আরশের প্রতিপালক",
      hi: "अल्लाह मेरे लिए काफ़ी है, उसके सिवा कोई माबूद नहीं, उसी पर मैंने भरोसा किया और वही अर्श अज़ीम का रब है",
      id: "Cukuplah Allah bagiku, tiada Tuhan selain Dia. Kepada-Nya aku bertawakal dan Dia adalah Tuhan yang memiliki Arsy yang agung"
    },
    transliteration: {
      en: "Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa rabbul 'arshil 'adheem",
      ur: "حسبی اللہ لا الہ الا ھو علیہ توکلت وھو رب العرش العظیم",
      bn: "হাসবিয়াল্লাহু লা ইলাহা ইল্লা হুওয়া আলাইহি তাওয়াক্কালতু ওয়া হুওয়া রাব্বুল আরশিল আযীম",
      hi: "हस्बियल्लाहु ला इलाहा इल्ला हुवा अलैहि तवक्कलतु व हुवा रब्बुल अर्शिल अज़ीम",
      id: "Hasbiyallaahu laa ilaaha illaa huwa 'alaihi tawakkaltu wa huwa rabbul 'arsyil 'azhiim"
    },
    benefits: {
      en: "Allah will grant whoever recites this seven times in the morning and evening whatever he desires in this world and the next",
      ur: "جو شخص صبح و شام سات مرتبہ یہ پڑھے، اللہ اسے دنیا اور آخرت کی مطلوبہ چیزیں عطا فرمائے گا",
      bn: "যে ব্যক্তি সকাল-সন্ধ্যায় সাতবার এটি পাঠ করবে, আল্লাহ তাকে দুনিয়া ও আখিরাতে যা চায় তা দান করবেন",
      hi: "जो शख़्स सुबह व शाम सात मर्तबा ये पढ़े, अल्लाह उसे दुनिया और आख़िरत की मतलूबा चीज़ें अता फ़रमाएगा",
      id: "Allah akan menganugerahkan kepada siapa yang membacanya tujuh kali di pagi dan sore hari apa pun yang diinginkannya di dunia dan akhirat"
    },
    repetitions: 7,
    category: "both",
    order: 8,
    references: [
      { bookId: "abu_dawud", number: 5081 }
    ]
  },
  {
    id: "allahumma_ma_asbaha",
    arabic: "اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
    translations: {
      en: "O Allah! Whatever blessing I or any of Your creation have risen upon, is from You alone, without partner, so for You is all praise and unto You all thanks",
      ur: "اے اللہ! جو بھی نعمت میرے پاس یا تیری کسی مخلوق کے پاس صبح ہوئی وہ صرف تیری طرف سے ہے، تیرا کوئی شریک نہیں، پس تیرے لیے ہی تمام تعریف اور تیرا ہی شکر ہے",
      bn: "হে আল্লাহ! আমার বা তোমার কোন সৃষ্টির কাছে যে নিয়ামত সকাল হয়েছে, তা একমাত্র তোমার পক্ষ থেকে, তোমার কোন শরীক নেই, সুতরাং তোমারই জন্য সকল প্রশংসা এবং তোমারই জন্য কৃতজ্ঞতা",
      hi: "ऐ अल्लाह! जो भी नेमत मेरे पास या तेरी किसी मख़लूक़ के पास सुबह हुई वो सिर्फ़ तेरी तरफ़ से है, तेरा कोई शरीक नहीं, पस तेरे लिए ही तमाम तारीफ़ और तेरा ही शुक्र है",
      id: "Ya Allah, nikmat apa pun yang aku atau makhluk-Mu yang lain terima di pagi ini, semuanya dari-Mu semata, tiada sekutu bagi-Mu. Maka bagi-Mu segala puji dan bagi-Mu segala syukur"
    },
    transliteration: {
      en: "Allahumma ma asbaha bi min ni'matin aw bi ahadin min khalqika famin ka wahdaka la sharika lak, falakal hamdu wa lakash-shukr",
      ur: "اللہم ما اصبح بی من نعمۃ او باحد من خلقک فمنک وحدک لا شریک لک فلک الحمد ولک الشکر",
      bn: "আল্লাহুম্মা মা আসবাহা বি মিন নি'মাতিন আও বি আহাদিন মিন খালকিকা ফামিনকা ওয়াহদাকা লা শারীকা লাক, ফালাকাল হামদু ওয়া লাকাশ শুকর",
      hi: "अल्लाहुम्मा मा असबहा बी मिन निअमतिन औ बि अहदिन मिन ख़ल्क़िका फ़मिन्का वहदका ला शरीका लक, फ़लकल हम्दु व लकश शुक्र",
      id: "Allaahumma maa ashbaha bii min ni'matin aw bi ahadin min khalqika fa minka wahdaka laa syariika lak, falakal hamdu wa lakasy syukru"
    },
    benefits: {
      en: "Whoever says this in the morning has indeed offered his thanks for the day",
      ur: "جس نے صبح یہ پڑھا اس نے دن کا شکر ادا کر دیا",
      bn: "যে ব্যক্তি সকালে এটি বলে সে প্রকৃতপক্ষে দিনের জন্য কৃতজ্ঞতা প্রকাশ করে",
      hi: "जिसने सुबह ये पढ़ा उसने दिन का शुक्र अदा कर दिया",
      id: "Barangsiapa yang mengucapkannya di pagi hari, sungguh ia telah menunaikan syukur untuk hari itu"
    },
    repetitions: 1,
    category: "morning",
    order: 10,
    references: [
      { bookId: "abu_dawud", number: 5073 }
    ]
  },
  {
    id: "allahumma_ma_amsa",
    arabic: "اللَّهُمَّ مَا أَمْسَىٰ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
    translations: {
      en: "O Allah! Whatever blessing I or any of Your creation have entered upon the evening with, is from You alone, without partner, so for You is all praise and unto You all thanks",
      ur: "اے اللہ! جو بھی نعمت میرے پاس یا تیری کسی مخلوق کے پاس شام ہوئی وہ صرف تیری طرف سے ہے، تیرا کوئی شریک نہیں، پس تیرے لیے ہی تمام تعریف اور تیرا ہی شکر ہے",
      bn: "হে আল্লাহ! আমার বা তোমার কোন সৃষ্টির কাছে যে নিয়ামত সন্ধ্যা হয়েছে, তা একমাত্র তোমার পক্ষ থেকে, তোমার কোন শরীক নেই, সুতরাং তোমারই জন্য সকল প্রশংসা এবং তোমারই জন্য কৃতজ্ঞতা",
      hi: "ऐ अल्लाह! जो भी नेमत मेरे पास या तेरी किसी मख़लूक़ के पास शाम हुई वो सिर्फ़ तेरी तरफ़ से है, तेरा कोई शरीक नहीं, पस तेरे लिए ही तमाम तारीफ़ और तेरा ही शुक्र है",
      id: "Ya Allah, nikmat apa pun yang aku atau makhluk-Mu yang lain terima di sore ini, semuanya dari-Mu semata, tiada sekutu bagi-Mu. Maka bagi-Mu segala puji dan bagi-Mu segala syukur"
    },
    transliteration: {
      en: "Allahumma ma amsa bi min ni'matin aw bi ahadin min khalqika famin ka wahdaka la sharika lak, falakal hamdu wa lakash-shukr",
      ur: "اللہم ما امسی بی من نعمۃ او باحد من خلقک فمنک وحدک لا شریک لک فلک الحمد ولک الشکر",
      bn: "আল্লাহুম্মা মা আমসা বি মিন নি'মাতিন আও বি আহাদিন মিন খালকিকা ফামিনকা ওয়াহদাকা লা শারীকা লাক, ফালাকাল হামদু ওয়া লাকাশ শুকর",
      hi: "अल्लाहुम्मा मा अमसा बी मिन निअमतिन औ बि अहदिन मिन ख़ल्क़िका फ़मिन्का वहदका ला शरीका लक, फ़लकल हम्दु व लकश शुक्र",
      id: "Allaahumma maa amsaa bii min ni'matin aw bi ahadin min khalqika fa minka wahdaka laa syariika lak, falakal hamdu wa lakasy syukru"
    },
    benefits: {
      en: "Whoever says this in the evening has indeed offered his thanks for the night",
      ur: "جس نے شام میں یہ پڑھا اس نے رات کا شکر ادا کر دیا",
      bn: "যে ব্যক্তি সন্ধ্যায় এটি বলে সে প্রকৃতপক্ষে রাতের জন্য কৃতজ্ঞতা প্রকাশ করে",
      hi: "जिसने शाम में ये पढ़ा उसने रात का शुक्र अदा कर दिया",
      id: "Barangsiapa yang mengucapkannya di sore hari, sungguh ia telah menunaikan syukur untuk malam itu"
    },
    repetitions: 1,
    category: "evening",
    order: 11,
    references: [
      { bookId: "abu_dawud", number: 5073 }
    ]
  },
  {
    id: "allahumma_bika_asbahna",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    translations: {
      en: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection",
      ur: "اے اللہ! تیری مدد سے ہم نے صبح کی اور تیری مدد سے ہم نے شام کی، تیری مدد سے ہم زندہ ہیں اور تیری مدد سے ہم مریں گے اور تیری طرف ہی اٹھنا ہے",
      bn: "হে আল্লাহ! তোমার সাহায্যে আমরা সকাল করি এবং তোমার সাহায্যে আমরা সন্ধ্যা করি। তোমার সাহায্যে আমরা বেঁচে থাকি এবং তোমার সাহায্যে আমরা মৃত্যুবরণ করি। আর তোমার দিকেই পুনরুত্থান",
      hi: "ऐ अल्लाह! तेरी मदद से हमने सुबह की और तेरी मदद से हमने शाम की, तेरी मदद से हम ज़िन्दा हैं और तेरी मदद से हम मरेंगे और तेरी तरफ़ ही उठना है",
      id: "Ya Allah, dengan pertolongan-Mu kami memasuki waktu pagi, dengan pertolongan-Mu kami memasuki waktu sore, dengan kehendak-Mu kami hidup, dengan kehendak-Mu kami mati, dan kepada-Mu kami dibangkitkan"
    },
    transliteration: {
      en: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu wa ilaykan nushur",
      ur: "اللہم بک اصبحنا وبک امسینا وبک نحیا وبک نموت والیک النشور",
      bn: "আল্লাহুম্মা বিকা আসবাহনা ওয়া বিকা আমসাইনা ওয়া বিকা নাহইয়া ওয়া বিকা নামূতু ওয়া ইলাইকান নুশূর",
      hi: "अल्लाहुम्मा बिका असबहना व बिका अमसैना व बिका नहया व बिका नमूतु व इलैकन नुशूर",
      id: "Allaahumma bika ashbahnaa wa bika amsainaa wa bika nahyaa wa bika namuutu wa ilaikan nusyuur"
    },
    benefits: {
      en: "Comprehensive remembrance acknowledging Allah's complete control over life, death and resurrection",
      ur: "جامع ذکر جو اللہ کی زندگی، موت اور قیامت پر مکمل قدرت کا اعتراف ہے",
      bn: "জীবন, মৃত্যু এবং পুনরুত্থানের উপর আল্লাহর সম্পূর্ণ নিয়ন্ত্রণ স্বীকার করে ব্যাপক জিকির",
      hi: "जामेअ ज़िक्र जो अल्लाह की ज़िन्दगी, मौत और क़यामत पर मुकम्मल क़ुदरत का एतराफ़ है",
      id: "Dzikir komprehensif yang mengakui kekuasaan penuh Allah atas kehidupan, kematian, dan kebangkitan"
    },
    repetitions: 1,
    category: "morning",
    order: 13,
    references: [
      { bookId: "tirmidhi", number: 3391 }
    ]
  },
  {
    id: "allahumma_bika_amsayna",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    translations: {
      en: "O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the final destination",
      ur: "اے اللہ! تیری مدد سے ہم نے شام کی اور تیری مدد سے ہم نے صبح کی، تیری مدد سے ہم زندہ ہیں اور تیری مدد سے ہم مریں گے اور تیری طرف ہی لوٹنا ہے",
      bn: "হে আল্লাহ! তোমার সাহায্যে আমরা সন্ধ্যা করি এবং তোমার সাহায্যে আমরা সকাল করি। তোমার সাহায্যে আমরা বেঁচে থাকি এবং তোমার সাহায্যে আমরা মৃত্যুবরণ করি। আর তোমার দিকেই প্রত্যাবর্তন",
      hi: "ऐ अल्लाह! तेरी मदद से हमने शाम की और तेरी मदद से हमने सुबह की, तेरी मदद से हम ज़िन्दा हैं और तेरी मदद से हम मरेंगे और तेरी तरफ़ ही लौटना है",
      id: "Ya Allah, dengan pertolongan-Mu kami memasuki waktu sore, dengan pertolongan-Mu kami memasuki waktu pagi, dengan kehendak-Mu kami hidup, dengan kehendak-Mu kami mati, dan kepada-Mu tempat kembali"
    },
    transliteration: {
      en: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilaykal maseer",
      ur: "اللہم بک امسینا وبک اصبحنا وبک نحیا وبک نموت والیک المصیر",
      bn: "আল্লাহুম্মা বিকা আমসাইনা ওয়া বিকা আসবাহনা ওয়া বিকা নাহইয়া ওয়া বিকা নামূতু ওয়া ইলাইকাল মাসীর",
      hi: "अल्लाहुम्मा बिका अमसैना व बिका असबहना व बिका नहया व बिका नमूतु व इलैकल मसीर",
      id: "Allaahumma bika amsainaa wa bika ashbahnaa wa bika nahyaa wa bika namuutu wa ilaikal mashiir"
    },
    benefits: {
      en: "Evening remembrance acknowledging Allah's complete control over all affairs",
      ur: "شام کا ذکر جو اللہ کی تمام معاملات پر مکمل قدرت کا اعتراف ہے",
      bn: "সন্ধ্যার জিকির যা সকল বিষয়ে আল্লাহর সম্পূর্ণ নিয়ন্ত্রণ স্বীকার করে",
      hi: "शाम का ज़िक्र जो अल्लाह की तमाम मामलात पर मुकम्मल क़ुदरत का एतराफ़ है",
      id: "Dzikir sore yang mengakui kekuasaan penuh Allah atas segala urusan"
    },
    repetitions: 1,
    category: "evening",
    order: 13,
    references: [
      { bookId: "tirmidhi", number: 3391 }
    ]
  },
  {
    id: "allahumma_aafini_fee_badani",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي لَا إِلَٰهَ إِلَّا أَنْتَ",
    translations: {
      en: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. There is no deity except You",
      ur: "اے اللہ! مجھے میرے بدن میں عافیت دے، اے اللہ! مجھے میری سماعت میں عافیت دے، اے اللہ! مجھے میری بصارت میں عافیت دے، تیرے سوا کوئی معبود نہیں",
      bn: "হে আল্লাহ! আমাকে আমার শরীরে সুস্থতা দান করুন। হে আল্লাহ! আমাকে আমার শ্রবণশক্তিতে সুস্থতা দান করুন। হে আল্লাহ! আমাকে আমার দৃষ্টিশক্তিতে সুস্থতা দান করুন। আপনি ছাড়া কোন উপাস্য নেই",
      hi: "ऐ अल्लाह! मुझे मेरे बदन में आफ़ियत दे, ऐ अल्लाह! मुझे मेरी सुनने की ताक़त में आफ़ियत दे, ऐ अल्लाह! मुझे मेरी देखने की ताक़त में आफ़ियत दे, तेरे सिवा कोई माबूद नहीं",
      id: "Ya Allah, berilah aku kesehatan pada badanku. Ya Allah, berilah aku kesehatan pada pendengaranku. Ya Allah, berilah aku kesehatan pada penglihatanku. Tiada Tuhan selain Engkau"
    },
    transliteration: {
      en: "Allahumma 'aafini fee badani, Allahumma 'aafini fee sam'i, Allahumma 'aafini fee basari, la ilaha illa ant",
      ur: "اللہم عافنی فی بدنی اللہم عافنی فی سمعی اللہم عافنی فی بصری لا الہ الا انت",
      bn: "আল্লাহুম্মা আফিনী ফী বাদানী, আল্লাহুম্মা আফিনী ফী সাম'ঈ, আল্লাহুম্মা আফিনী ফী বাসারী, লা ইলাহা ইল্লা আনত",
      hi: "अल्लाहुम्मा आफ़िनी फ़ी बदनी, अल्लाहुम्मा आफ़िनी फ़ी सम्ई, अल्लाहुम्मा आफ़िनी फ़ि बसरी, ला इलाहा इल्ला अन्त",
      id: "Allaahumma 'aafinii fii badanii, Allaahumma 'aafinii fii sam'ii, Allaahumma 'aafinii fii basharii, laa ilaaha illaa anta"
    },
    benefits: {
      en: "Protection and wellness for the body, hearing and sight",
      ur: "بدن، سماعت اور بصارت کے لیے حفاظت اور عافیت",
      bn: "শরীর, শ্রবণ এবং দৃষ্টির জন্য সুরক্ষা এবং সুস্থতা",
      hi: "बदन, सुनने और देखने की ताक़त के लिए हिफ़ाज़त और आफ़ियत",
      id: "Perlindungan dan kesehatan untuk badan, pendengaran, dan penglihatan"
    },
    repetitions: 3,
    category: "both",
    order: 20,
    references: [
      { bookId: "abu_dawud", number: 5090 }
    ]
  },
  {
    id: "allahumma_inni_audhu_kufr",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ لَا إِلَٰهَ إِلَّا أَنْتَ",
    translations: {
      en: "O Allah, I seek refuge in You from disbelief and poverty. O Allah, I seek refuge in You from the punishment of the grave. There is no deity except You",
      ur: "اے اللہ! میں تیری پناہ چاہتا ہوں کفر سے اور فقر سے، اے اللہ! میں تیری پناہ چاہتا ہوں قبر کے عذاب سے، تیرے سوا کوئی معبود نہیں",
      bn: "হে আল্লাহ! আমি আপনার কাছে কুফর এবং দারিদ্র্য থেকে আশ্রয় চাই। হে আল্লাহ! আমি আপনার কাছে কবরের আযাব থেকে আশ্রয় চাই। আপনি ছাড়া কোন উপাস্য নেই",
      hi: "ऐ अल्लाह! मैं तेरी पनाह चाहता हूं कुफ़्र से और फ़क़्र से, ऐ अल्लाह! मैं तेरी पनाह चाहता हूं क़ब्र के अज़ाब से, तेरे सिवा कोई माबूद नहीं",
      id: "Ya Allah, aku berlindung kepada-Mu dari kekufuran dan kefakiran. Ya Allah, aku berlindung kepada-Mu dari siksa kubur. Tiada Tuhan selain Engkau"
    },
    transliteration: {
      en: "Allahumma inni a'udhu bika minal kufri wal faqr, Allahumma inni a'udhu bika min 'adhabil qabr, la ilaha illa ant",
      ur: "اللہم انی اعوذ بک من الکفر والفقر اللہم انی اعوذ بک من عذاب القبر لا الہ الا انت",
      bn: "আল্লাহুম্মা ইন্নী আউযু বিকা মিনাল কুফরি ওয়াল ফাকর, আল্লাহুম্মা ইন্নী আউযু বিকা মিন আযাবিল কাবর, লা ইলাহা ইল্লা আনত",
      hi: "अल्लाहुम्मा इन्नी अऊज़ु बिका मिनल कुफ़्रि वल फ़क़्र, अल्लाहुम्मा इन्नी अऊज़ु बिका मिन अज़ाबिल क़ब्र, ला इलाहा इल्ला अन्त",
      id: "Allaahumma innii a'uudzu bika minal kufri wal faqri, Allaahumma innii a'uudzu bika min 'adzaabil qabri, laa ilaaha illaa anta"
    },
    benefits: {
      en: "Protection from disbelief, poverty and the punishment of the grave",
      ur: "کفر، فقر اور قبر کے عذاب سے حفاظت",
      bn: "কুফর, দারিদ্র্য এবং কবরের আযাব থেকে সুরক্ষা",
      hi: "कुफ़्र, फ़क़्र और क़ब्र के अज़ाब से हिफ़ाज़त",
      id: "Perlindungan dari kekufuran, kefakiran, dan siksa kubur"
    },
    repetitions: 3,
    category: "both",
    order: 21,
    references: [
      { bookId: "abu_dawud", number: 5090 }
    ]
  },
  {
    id: "durood_sharif_10",
    arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَّجِيدٌ اللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَّجِيدٌ",
    translations: {
      en: "O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious",
      ur: "اے اللہ! رحمت نازل فرما محمد پر اور آل محمد پر جیسا کہ تو نے رحمت نازل فرمائی ابراہیم پر اور آل ابراہیم پر، بے شک تو تعریف والا بزرگی والا ہے۔ اے اللہ! برکت نازل فرما محمد پر اور آل محمد پر جیسا کہ تو نے برکت نازل فرمائی ابراہیم پر اور آل ابراہیم پر، بے شک تو تعریف والا بزرگی والا ہے",
      bn: "হে আল্লাহ! মুহাম্মাদ ও তাঁর পরিবারের উপর রহমত বর্ষণ করুন, যেমন আপনি ইব্রাহীম ও তাঁর পরিবারের উপর রহমত বর্ষণ করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহিমান্বিত। হে আল্লাহ! মুহাম্মাদ ও তাঁর পরিবারের উপর বরকত দান করুন, যেমন আপনি ইব্রাহীম ও তাঁর পরিবারের উপর বরকত দান করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহিমান্বিত",
      hi: "ऐ अल्लाह! रहमत नाज़िल फ़रमा मुहम्मद पर और आले मुहम्मद पर जैसा कि तूने रहमत नाज़िल फ़रमाई इब्राहीम पर और आले इब्राहीम पर, बेशक तू तारीफ़ वाला बुज़ुर्गी वाला है। ऐ अल्लाह! बरकत नाज़िल फ़रमा मुहम्मद पर और आले मुहम्मद पर जैसा कि तूने बरकत नाज़िल फ़रमाई इब्राहीम पर और आले इब्राहीम पर, बेशक तू तारीफ़ वाला बुज़ुर्गी वाला है",
      id: "Ya Allah, limpahkanlah shalawat kepada Muhammad dan keluarga Muhammad sebagaimana Engkau telah melimpahkan shalawat kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkahilah Muhammad dan keluarga Muhammad sebagaimana Engkau telah memberkahi Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia"
    },
    transliteration: {
      en: "Allahumma salli 'ala Muhammadin wa 'ala aali Muhammadin kama sallayta 'ala Ibrahima wa 'ala aali Ibrahima innaka Hameedum Majeed. Allahumma barik 'ala Muhammadin wa 'ala aali Muhammadin kama barakta 'ala Ibrahima wa 'ala aali Ibrahima innaka Hameedum Majeed",
      ur: "اللہم صل علی محمد و علی آل محمد کما صلیت علی ابراہیم و علی آل ابراہیم انک حمید مجید۔ اللہم بارک علی محمد و علی آل محمد کما بارکت علی ابراہیم و علی آل ابراہیم انک حمید مجید",
      bn: "আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদিন কামা সাল্লাইতা আলা ইবরাহীমা ওয়া আলা আলি ইবরাহীমা ইন্নাকা হামীদুম মাজীদ। আল্লাহুম্মা বারিক আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদিন কামা বারাকতা আলা ইবরাহীমা ওয়া আলা আলি ইবরাহীমা ইন্নাকা হামীদুম মাজীদ",
      hi: "अल्लाहुम्मा सल्लि अला मुहम्मदिन व अला आलि मुहम्मदिन कमा सल्लैता अला इब्राहीमा व अला आलि इब्राहीमा इन्नका हमीदुम मजीद। अल्लाहुम्मा बारिक अला मुहम्मदिन व अला आलि मुहम्मदिन कमा बारक्ता अला इब्राहीमा व अला आलि इब्राहीमा इन्नका हमीदुम मजीद",
      id: "Allaahumma shalli 'alaa Muhammadin wa 'alaa aali Muhammadin kamaa shallaita 'alaa Ibraahiima wa 'alaa aali Ibraahiima innaka Hamiidun Majiid. Allaahumma baarik 'alaa Muhammadin wa 'alaa aali Muhammadin kamaa baarakta 'alaa Ibraahiima wa 'alaa aali Ibraahiima innaka Hamiidun Majiid"
    },
    benefits: {
      en: "The one who recites Darood Sharif deserves the intercession of the Prophet ﷺ. Praising Allah and sending Salat upon his beloved ﷺ are the best sources of the acceptance of the supplications",
      ur: "درود شریف پڑھنے والا نبی ﷺ کی شفاعت کا حقدار ہو جاتا ہے۔ اللہ کی حمد اور اس کے محبوب ﷺ پر درود شریف پڑھنا، دعاؤں کی قبولیت کا بہترین ذریعہ ہے",
      bn: "দরূদ শরীফ পাঠকারী নবী ﷺ এর শাফায়াতের হকদার হয়ে যায়। আল্লাহর প্রশংসা করা এবং তাঁর প্রিয়তম ﷺ এর উপর সালাত পাঠানো দুআ কবুলের সর্বোত্তম উৎস",
      hi: "दरूद शरीफ़ पढ़ने वाला शख़्स शफ़ाअत ﷺ की शफ़ाअत का हक़दार हो जाता है। अल्लाह की हम्द और उसके महबूब ﷺ पर दरूद शरीफ़ पढ़ना, दुआओं की कुबूलियत का बेहतरीन ज़रिया है",
      id: "Barangsiapa yang membaca shalawat akan mendapat syafaat Nabi ﷺ. Memuji Allah dan bershalawat kepada kekasih-Nya ﷺ adalah sumber terbaik diterimanya doa"
    },
    repetitions: 10,
    category: "both",
    order: 24,
    references: [
      { bookId: "bukhari", number: 3370 },
      { bookId: "muslim", number: 406 }
    ]
  },
  {
    id: "four_kalimat_100",
    arabic: "سُبْحَانَ اللَّهِ ۝ الْحَمْدُ لِلَّهِ ۝ اللَّهُ أَكْبَرُ ۝ لَا إِلَٰهَ إِلَّا اللَّهُ",
    translations: {
      en: "Glory be to Allah, All praise is for Allah, Allah is the Greatest, There is no deity except Allah",
      ur: "اللہ پاک ہے، تمام تعریفیں اللہ کے لیے ہیں، اللہ سب سے بڑا ہے، نہیں کوئی معبود سوائے اللہ کے",
      bn: "আল্লাহ পবিত্র, সমস্ত প্রশংসা আল্লাহর জন্য, আল্লাহ সর্বমহান, আল্লাহ ছাড়া কোন মাবুদ নেই",
      hi: "अल्लाह पाक है, तमाम तारीफ़ें अल्लाह के लिए हैं, अल्लाह सबसे बड़ा है, नहीं कोई माबूद सिवाए अल्लाह के",
      id: "Maha Suci Allah, Segala puji bagi Allah, Allah Maha Besar, Tiada Tuhan selain Allah"
    },
    transliteration: {
      en: "SubhanAllah, Alhamdulillah, Allahu Akbar, La ilaha illallah",
      ur: "سبحان اللہ، الحمد للہ، اللہ اکبر، لا الہ الا اللہ",
      bn: "সুবহানাল্লাহ, আলহামদুলিল্লাহ, আল্লাহু আকবার, লা ইলাহা ইল্লাল্লাহ",
      hi: "सुब्हानल्लाह, अल्हम्दुलिल्लाह, अल्लाहु अकबर, ला इलाहा इल्लल्लाह",
      id: "Subhaanallaah, Alhamdulillaah, Allaahu Akbar, Laa ilaaha illallaah"
    },
    benefits: {
      en: "Reward of freeing 100 slaves, reward of sending 100 horses in Jihad, reward of sacrificing 100 camels in the cause of Allah, it fills the earth and the heaven",
      ur: "100 غلام آزاد کرنے کا ثواب، 100 گھوڑے جہاد میں بھیجنے کا ثواب، 100 اونٹ اللہ کی راہ میں قربان کرنے کا ثواب، زمین و آسمان بھر جاتے ہیں",
      bn: "১০০ গোলাম আজাদ করার সওয়াব, ১০০ ঘোড়া জিহাদে পাঠানোর সওয়াব, আল্লাহর রাস্তায় ১০০ উট কুরবানী করার সওয়াব, জমিন ও আসমান পূর্ণ হয়ে যায়",
      hi: "100 गुलाम आज़ाद करने का सवाब, 100 घोड़े जिहाद में भेजने का सवाब, 100 ऊंट अल्लाह की राह में कुर्बान करने का सवाब, ज़मीन व आसमान भर जाते हैं",
      id: "Pahala memerdekakan 100 budak, pahala mengirim 100 kuda untuk jihad, pahala menyembelih 100 unta di jalan Allah, memenuhi langit dan bumi"
    },
    repetitions: 100,
    category: "both",
    order: 19,
    references: [
      { bookId: "nasai_kubra", number: 10680 }
    ]
  },
  {
    id: "allahumma_inni_afiyah",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي اللَّهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي اللَّهُمَّ احْفَظْنِي مِن بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَن شِمَالِي وَمِن فَوْقِي وَأَعُوذُ بِعَظَمَتِكَ أَن أُغْتَالَ مِن تَحْتِي",
    translations: {
      en: "O Allah, I ask You for well being in this world and in the Hereafter. O Allah, I ask You for forgiveness and well being in my religious commitment, my worldly affairs, my family and my wealth. O Allah, conceal my fault and keep me safe from the things I fear. O Allah, protect me from in front and behind, from my right and my left and from above. I seek refuge in Your might from any unexpected harm coming from beneath me",
      ur: "اے اللہ! میں تجھ سے دنیا اور آخرت میں عافیت کا سوال کرتا ہوں۔ اے اللہ! میں تجھ سے عفو اور عافیت کا سوال کرتا ہوں میری دین میں اور میری دنیا میں اور میرے گھر والوں میں اور میرے مال میں۔ اے اللہ! میرے عیبوں کو چھپا دے اور میرے خوف کو امن میں بدل دے۔ اے اللہ! میری حفاظت فرما میرے آگے سے اور میرے پیچھے سے اور میرے دائیں سے اور میرے بائیں سے اور میرے اوپر سے اور میں تیری عظمت کی پناہ مانگتا ہوں کہ میں اپنے نیچے سے ہلاک کیا جاؤں",
      bn: "হে আল্লাহ! আমি তোমার কাছে দুনিয়া ও আখিরাতে সুস্থতা কামনা করছি। হে আল্লাহ, আমি তোমার কাছে আমার ধর্মীয় অঙ্গীকার, আমার পার্থিব বিষয়, আমার পরিবার এবং আমার সম্পদের জন্য ক্ষমা ও সুস্থতা কামনা করছি। হে আল্লাহ, আমার দোষ গোপন করুন এবং আমি যা ভয় পাই তা থেকে আমাকে রক্ষা করুন। হে আল্লাহ, আমাকে রক্ষা করুন আমার সামনে ও পেছন থেকে, আমার ডান-বাম ও উপর থেকে। আমার নীচ থেকে আসা কোন অপ্রত্যাশিত ক্ষতি থেকে আমি তোমার শক্তিতে আশ্রয় চাই",
      hi: "ऐ अल्लाह! मैं तुझसे दुनिया और आख़िरत में आफ़ियत का सवाल करता हूँ। ऐ अल्लाह! मैं तुझसे अफ़्व और आफ़ियत का सवाल करता हूँ मेरे दीन में और मेरी दुनिया में और मेरे घर वालों में और मेरे माल में। ऐ अल्लाह! मेरे ऐबों को छुपा दे और मेरे ख़ौफ़ को अम्न में बदल दे। ऐ अल्लाह! मेरी हिफ़ाज़त फ़रमा मेरे आगे से और मेरे पीछे से और मेरे दाएं से और मेरे बाएं से और मेरे ऊपर से और मैं तेरी अज़मत की पनाह मांगता हूँ कि मैं अपने नीचे से हलाक किया जाऊं",
      id: "Ya Allah, aku memohon kepada-Mu keselamatan di dunia dan akhirat. Ya Allah, aku memohon kepada-Mu ampunan dan keselamatan dalam agamaku, duniaku, keluargaku dan hartaku. Ya Allah, tutupilah auratku (aib dan sesuatu yang tidak layak dilihat orang) dan tenteramkanlah aku dari rasa takut. Ya Allah, peliharalah aku dari muka, belakang, kanan, kiri dan dari atasku. Aku berlindung dengan kebesaran-Mu, agar aku tidak disambar dari bawahku"
    },
    transliteration: {
      en: "Allahumma inni as'alukal 'afiyata fid dunya wal akhirah. Allahumma inni as'alukal 'afwa wal 'afiyata fi dini wa dunyaya wa ahli wa mali. Allahummastur 'awrati wa amin raw'ati. Allahumma hfazni min bayni yadayya wa min khalfi wa 'an yamini wa 'an shimali wa min fawqi wa a'udhu bi'azamatika an ughtala min tahti",
      ur: "اللہم انی اسالک العافیۃ فی الدنیا والآخرۃ اللہم انی اسالک العفو والعافیۃ فی دینی ودنیای واھلی ومالی اللہم استر عوراتی وآمن روعاتی اللہم احفظنی من بین یدی ومن خلفی وعن یمینی وعن شمالی ومن فوقی واعوذ بعظمتک ان اغتال من تحتی",
      bn: "আল্লাহুম্মা ইন্নী আস'আলুকাল আফিয়াতা ফিদ দুনিয়া ওয়াল আখিরাহ। আল্লাহুম্মা ইন্নী আস'আলুকাল আফওয়া ওয়াল আফিয়াতা ফী দীনী ওয়া দুনয়ায়া ওয়া আহলী ওয়া মালী। আল্লাহুম্মাসতুর আওরাতী ওয়া আমিন রাওআতী। আল্লাহুম্মাহফাযনী মিন বাইনি ইয়াদাইয়া ওয়া মিন খালফী ওয়া আন ইয়ামীনী ওয়া আন শিমালী ওয়া মিন ফাওকী ওয়া আউযু বিআযামাতিকা আন উগতালা মিন তাহতী",
      hi: "अल्लाहुम्मा इन्नी अस्अलुकल आफ़ियता फ़िद दुन्या वल आख़िरह। अल्लाहुम्मा इन्नी अस्अलुकल अफ़्वा वल आफ़ियता फ़ी दीनी व दुन्याया व अहली व माली। अल्लाहुम्मस्तुर औराती व आमिन रौआती। अल्लाहुम्माह्फ़ज़नी मिन बैनि यदैया व मिन ख़ल्फ़ी व अन यमीनी व अन शिमाली व मिन फ़ौक़ी व अऊज़ु बिअज़मतिका अन उग़ताला मिन तहती",
      id: "Allaahumma innii as'alukal 'aafiyata fid dunyaa wal aakhirati. Allaahumma innii as'alukal 'afwa wal 'aafiyata fii diinii wa dunyaaya wa ahlii wa maalii. Allaahummastuur 'auraatii wa aamin raw'aatii. Allaahummaḥfaẓnii mim baini yadayya wa min khalfii wa 'an yamiinii wa 'an syimaalii wa min fauqii wa a'uudzu bi'aẓamatika an ughtaala min taḥtii"
    },
    benefits: {
      en: "Comprehensive protection and wellbeing in all aspects of life",
      ur: "زندگی کے تمام پہلوؤں میں مکمل حفاظت اور عافیت",
      bn: "জীবনের সকল দিকে সার্বিক সুরক্ষা ও কল্যাণ",
      hi: "ज़िन्दगी के तमाम पहलुओं में मुकम्मल हिफ़ाज़त और आफ़ियत",
      id: "Perlindungan dan kesejahteraan menyeluruh dalam segala aspek kehidupan"
    },
    repetitions: 1,
    category: "both",
    order: 14,
    references: [
      { bookId: "abu_dawud", number: 5074 }
    ]
  },
  {
    id: "allahumma_aalimal_ghayb",
    arabic: "اللَّهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ أَشْهَدُ أَن لَّا إِلَٰهَ إِلَّا أَنتَ أَعُوذُ بِكَ مِن شَرِّ نَفْسِي وَمِن شَرِّ الشَّيْطَانِ وَشِرْكِهِ وَأَنْ أَقْتَرِفَ عَلَىٰ نَفْسِي سُوءًا أَوْ أَجُرَّهُ إِلَىٰ مُسْلِمٍ",
    translations: {
      en: "O Allah! Knower of the Unseen and the Seen, Originator of the heavens and the earth, Lord of everything and its Possessor also, I bear witness that there is none worthy of worship except You. I seek refuge in You from the evil of my soul and the from the evil of Shaitan and his participation (in my works) and that I should do some evil to myself or bring it upon a Muslim",
      ur: "اے اللہ! جاننے والے غیب اور حاضر کو، پیدا کرنے والے آسمانوں اور زمین کو، ہر چیز کا رب اور مالک، میں گواہی دیتا ہوں کہ نہیں کوئی معبود سوائے تیرے، میں تیری پناہ پکڑتا ہوں اپنے نفس کی برائی سے اور شیطان کے شر سے اور اس کے شرک سے اور اس سے کہ میں اپنے آپ پر کوئی برائی کروں یا کسی مسلمان کی طرف کھینچوں",
      bn: "হে আল্লাহ! গায়েব ও হাযিরের জ্ঞানী, আসমান ও জমিনের স্রষ্টা, সকল কিছুর পালনকর্তা এবং এর মালিকও, আমি সাক্ষ্য দিচ্ছি যে, আপনি ছাড়া ইবাদতের যোগ্য কেউ নেই। আমি আপনার কাছে আমার নফসের অনিষ্ট থেকে এবং শয়তানের অনিষ্ট থেকে এবং তার শিরক থেকে আশ্রয় চাই এবং এ থেকেও যে আমি নিজের উপর কোন মন্দ করি বা কোন মুসলিমের দিকে টেনে আনি",
      hi: "ऐ अल्लाह! जानने वाले ग़ैब और हाज़िर के, पैदा करने वाले आसमानों और ज़मीन के, हर चीज़ के रब और मालिक भी, मैं गवाही देता हूँ कि नहीं है कोई माबूद मगर तू, मैं तेरी पनाह में आता हूँ अपने नफ़्स की बुराई से और शैतान के शर से और उसके शिर्क से और इससे कि मैं अपने ऊपर कोई बुराई करूं या किसी मुसलमान की तरफ़ खींचूं",
      id: "Ya Allah, Yang Maha Mengetahui yang ghaib dan yang nyata, Pencipta langit dan bumi, Tuhan segala sesuatu dan Yang Merajainya. Aku bersaksi bahwa tidak ada Tuhan yang berhak disembah kecuali Engkau. Aku berlindung kepada-Mu dari kejahatan diriku, dari kejahatan setan dan sekutunya, dan dari berbuat kejahatan terhadap diriku atau menimpakan kejahatan kepada seorang muslim"
    },
    transliteration: {
      en: "Allahumma 'alimal ghaybi wash shahadah, Fatiras samawati wal ard, Rabba kulli shay'in wa malikah, ashhadu an la ilaha illa ant, a'udhu bika min sharri nafsi wa min sharrish shaytani wa shirkihi wa an aqtarifa 'ala nafsi su'an aw ajurrahu ila muslim",
      ur: "اللہم عالم الغیب والشہادۃ فاطر السماوات والارض رب کل شیء وملیکہ اشہد ان لا الہ الا انت اعوذ بک من شر نفسی ومن شر الشیطان وشرکہ وان اقترف علی نفسی سوءا او اجرہ الی مسلم",
      bn: "আল্লাহুম্মা আলিমাল গাইবি ওয়াশ শাহাদাহ, ফাতিরাস সামাওয়াতি ওয়াল আরদ, রব্বা কুল্লি শাইয়িন ওয়া মালিকাহ, আশহাদু আন লা ইলাহা ইল্লা আনত, আউযু বিকা মিন শাররি নাফসী ওয়া মিন শাররিশ শায়তানি ওয়া শিরকিহী ওয়া আন আকতারিফা আলা নাফসী সূআন আও আজুররাহু ইলা মুসলিম",
      hi: "अल्लाहुम्मा आलिमल ग़ैबि वश शहादह, फ़ातिरस समावाति वल अर्ज़, रब्बा कुल्लि शैइन व मालिकह, अशहदु अन ला इलाहा इल्ला अन्त, अऊज़ु बिका मिन शर्रि नफ़्सी व मिन शर्रिश शैतानि व शिर्किही व अन अक़्तरिफ़ अला नफ़्सी सूअन औ अजुर्रहु इला मुस्लिम",
      id: "Allaahumma 'aalimal ghaibi wasy syahaadati, faathiras samaawaati wal ardhi, rabba kulli syai'in wa maliikahu, asyhadu an laa ilaaha illaa anta, a'uudzu bika min syarri nafsii wa min syarrisy syaithaani wa syirkihi wa an aqtarifa 'alaa nafsii suu'an aw ajurrahu ilaa muslim"
    },
    benefits: {
      en: "Protection from inner and outer evil influences",
      ur: "اندرونی اور بیرونی برائیوں سے حفاظت",
      bn: "অভ্যন্তরীণ এবং বাহ্যিক মন্দ প্রভাব থেকে সুরক্ষা",
      hi: "अंदरूनी और बैरूनी बुराइयों से हिफ़ाज़त",
      id: "Perlindungan dari pengaruh kejahatan dari dalam dan luar"
    },
    repetitions: 1,
    category: "both",
    order: 15,
    references: [
      { bookId: "tirmidhi", number: 3392 }
    ]
  },
  {
    id: "morning_evening_complete_dua",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَٰذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَٰذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ",
    translations: {
      en: "We have reached the morning and the Dominion belongs to Allah and praise be to Allah, none has the right to be worshipped but Allah alone with no partner or associate. He is the dominion, to Him is praise and He has power over all things. O Allah, I ask You for the good of this day and the good of what follows it. And I seek refuge with You for the evil of this day and the evil of what follows it. O Lord, I seek refuge with You from laziness and the evil of the old age. O Lord, I seek refuge with You from torment in the Fire and torment in the grave.",
      ur: "ہم نے صُبح کی اور بادشاہی اللہ کیلیے صبح ہوئی، اور تمام تعریفیں اللہ کیلیے ہیں، نہیں کوئی معبود سوائے اللہ کے، وہ اکیلا ہے، نہیں کوئی شریک اُسکا، اُسی کی بادشاہی ہے، اور اُسی کے لیے سب تعریفیں ہیں، اور وہ ہر چیز پر قادر ہے۔ اے رب! میں تجھ سے مانگتا ہوں اس دن میں جو خیر ہے اور جو خیر ہے اس کے بعد، اور میں تیری پناہ میں آتا ہوں اس دن کے شر سے اور جو شر ہے اس کے بعد۔ اے رب! میں تیری پناہ میں آتا ہوں سستی سے اور بڑھاپے کی برائی سے۔ اے رب! میں تیری پناہ میں آتا ہوں جہنم کے عذاب سے اور قبر کے عذاب سے",
      bn: "আমরা সকালে উপনীত হয়েছি এবং সার্বভৌমত্ব আল্লাহর জন্য এবং সমস্ত প্রশংসা আল্লাহর জন্য। আল্লাহ ছাড়া কোন উপাস্য নেই, তিনি একক, তাঁর কোন শরীক নেই। সার্বভৌমত্ব তাঁরই, প্রশংসা তাঁরই এবং তিনি সকল কিছুর উপর ক্ষমতাবান। হে আমার রব! আমি আপনার কাছে এই দিনের কল্যাণ এবং এর পরের কল্যাণ চাই। আর আমি আপনার কাছে আশ্রয় চাই এই দিনের অকল্যাণ এবং এর পরের অকল্যাণ থেকে। হে রব! আমি আপনার কাছে আশ্রয় চাই অলসতা এবং বার্ধক্যের মন্দ থেকে। হে রব! আমি আপনার কাছে আশ্রয় চাই জাহান্নামের শাস্তি এবং কবরের শাস্তি থেকে।",
      hi: "हमने सुबह की और बादशाही अल्लाह के लिए सुबह हुई, और तमाम तारीफ़ें अल्लाह के लिए हैं, नहीं कोई माबूद सिवाए अल्लाह के, वह अकेला है, नहीं कोई शरीक उसका, उसी की बादशाही है, और उसी के लिए सब तारीफ़ें हैं, और वह हर चीज़ पर क़ादिर है। ऐ रब! मैं तुझसे मांगता हूं इस दिन में जो ख़ैर है और जो ख़ैर है इसके बाद, और मैं तेरी पनाह में आता हूं इस दिन के शर से और जो शर है इसके बाद। ऐ रब! मैं तेरी पनाह में आता हूं सुस्ती से और बुढ़ापे की बुराई से। ऐ रब! मैं तेरी पनाह में आता हूं जहन्नम के अज़ाब से और क़ब्र के अज़ाब से",
      id: "Kami telah memasuki waktu pagi dan kerajaan hanya milik Allah, segala puji hanya milik Allah. Tidak ada Tuhan yang berhak disembah kecuali Allah Yang Maha Esa, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan bagi-Nya segala pujian. Dia Mahakuasa atas segala sesuatu. Wahai Tuhanku, aku mohon kepada-Mu kebaikan di hari ini dan kebaikan sesudahnya. Aku berlindung kepada-Mu dari keburukan hari ini dan keburukan sesudahnya. Wahai Tuhanku, aku berlindung kepada-Mu dari kemalasan dan keburukan di hari tua. Wahai Tuhanku, aku berlindung kepada-Mu dari siksaan di neraka dan siksaan di alam kubur"
    },
    transliteration: {
      en: "Asbahna wa asbahal mulku lillah walhamdulillah la ilaha illallahu wahdahu la sharika lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadir. Rabbi as'aluka khayra ma fi hadhal yawm wa khayra ma ba'dahu wa a'udhu bika min sharri ma fi hadhal yawm wa sharri ma ba'dahu. Rabbi a'udhu bika minal kasali wa su'il kibar. Rabbi a'udhu bika min 'adhabin fin nari wa 'adhabin fil qabr",
      ur: "اصبحنا واصبح الملک للہ والحمد للہ لا الہ الا اللہ وحدہ لا شریک لہ، لہ الملک ولہ الحمد وھو علی کل شیء قدیر، رب اسالک خیر ما فی ھذا الیوم وخیر ما بعدہ واعوذ بک من شر ما فی ھذا الیوم وشر ما بعدہ رب اعوذ بک من الکسل وسوء الکبر رب اعوذ بک من عذاب فی النار وعذاب فی القبر",
      bn: "আসবাহনা ওয়া আসবাহাল মুলকু লিল্লাহ ওয়াল হামদুলিল্লাহ লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারীকা লাহ, লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুওয়া আলা কুল্লি শাইয়িন কাদীর। রাব্বি আস'আলুকা খাইরা মা ফী হাযাল ইয়াওমি ওয়া খাইরা মা বা'দাহু ওয়া আউযু বিকা মিন শাররি মা ফী হাযাল ইয়াওমি ওয়া শাররি মা বা'দাহ। রাব্বি আউযু বিকা মিনাল কাসালি ওয়া সূইল কিবার। রাব্বি আউযু বিকা মিন আযাবিন ফিন নারি ওয়া আযাবিন ফিল কাবর",
      hi: "असबहना व असबहल मुल्कु लिल्लाह वल हम्दुलिल्लाह ला इलाहा इल्लल्लाहु वहदहु ला शरीका लह, लहुल मुल्कु व लहुल हम्दु व हुवा अला कुल्लि शैइन क़दीर। रब्बि अस्अलुका ख़ैरा मा फ़ी हाज़ल यौमि व ख़ैरा मा बअदहु व अऊज़ु बिका मिन शर्रि मा फ़ी हाज़ल यौमि व शर्रि मा बअदह। रब्बि अऊज़ु बिका मिनल कसलि व सूइल किबर। रब्बि अऊज़ु बिका मिन अज़ाबिन फ़िन नारि व अज़ाबिन फ़िल क़ब्र",
      id: "Ashbahnaa wa ashbahal mulku lillaah walhamdulillaah laa ilaaha illallaahu wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai'in qadiir. Rabbi as'aluka khaira maa fii haadzal yaumi wa khaira maa ba'dahu wa a'uudzu bika min syarri maa fii haadzal yaumi wa syarri maa ba'dahu. Rabbi a'uudzu bika minal kasali wa suu'il kibari. Rabbi a'uudzu bika min 'adzaabin fin naari wa 'adzaabin fil qabri"
    },
    benefits: {
      en: "Complete supplication for morning protection and blessings",
      ur: "صبح کی حفاظت اور برکات کے لیے مکمل دعا",
      bn: "সকালের সুরক্ষা এবং বরকতের জন্য সম্পূর্ণ দুআ",
      hi: "सुबह की हिफ़ाज़त और बरकात के लिए मुकम्मल दुआ",
      id: "Doa lengkap untuk perlindungan dan keberkahan di pagi hari"
    },
    repetitions: 1,
    category: "morning",
    order: 12,
    references: [
      { bookId: "muslim", number: 6908 }
    ]
  },
  {
    id: "surah_baqarah_last_2",
    arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ ۝ لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
    translations: {
      en: "The Messenger has believed in what was revealed to him from his Lord, and [so have] the believers. All of them have believed in Allah and His angels and His books and His messengers, [saying], 'We make no distinction between any of His messengers.' And they say, 'We hear and we obey. [We seek] Your forgiveness, our Lord, and to You is the [final] destination.' Allah does not charge a soul except [with that within] its capacity. It will have [the consequence of] what [good] it has gained, and it will bear [the consequence of] what [evil] it has earned. 'Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people.'",
      ur: "رسول ایمان لایا اس چیز پر جو اس کی طرف اس کے رب کی جانب سے نازل کی گئی اور مومن بھی، سب ایمان لائے اللہ پر اور اس کے فرشتوں پر اور اس کی کتابوں پر اور اس کے رسولوں پر، ہم اس کے رسولوں میں سے کسی میں فرق نہیں کرتے، اور وہ کہتے ہیں ہم نے سنا اور اطاعت کی، اے ہمارے رب تیری مغفرت چاہتے ہیں اور تیری ہی طرف لوٹنا ہے۔ اللہ کسی جان کو اس کی طاقت سے زیادہ تکلیف نہیں دیتا، اس کے لیے ہے جو اس نے کمایا اور اس کے اوپر ہے جو اس نے برائی کمائی، اے ہمارے رب ہماری گرفت نہ کر اگر ہم بھول جائیں یا خطا کریں، اے ہمارے رب ہم پر بوجھ نہ ڈال جیسا کہ تو نے ڈالا تھا ہم سے پہلے لوگوں پر، اے ہمارے رب ہم پر وہ بوجھ نہ ڈال جس کی ہمیں طاقت نہیں، اور ہمیں معاف کر دے اور ہمیں بخش دے اور ہم پر رحم کر، تو ہمارا مولا ہے پس ہماری مدد کر کافروں کی قوم پر",
      bn: "রাসূল ঈমান এনেছেন ঐ সমস্ত বিষয় সম্পর্কে যা তাঁর পালনকর্তার পক্ষ থেকে তাঁর কাছে অবতীর্ণ হয়েছে এবং মুমিনরাও। সকলেই বিশ্বাস রাখে আল্লাহর প্রতি, তাঁর ফেরেশতাদের প্রতি, তাঁর গ্রন্থসমূহের প্রতি এবং তাঁর রাসূলগণের প্রতি। তারা বলে: আমরা তাঁর রাসূলদের মধ্যে কোন তারতম্য করি না। তারা বলে: আমরা শুনেছি এবং কবুল করেছি। আমরা তোমার ক্ষমা চাই, হে আমাদের পালনকর্তা। তোমারই দিকে প্রত্যাবর্তন করতে হবে। আল্লাহ কাউকে তার সাধ্যাতীত কোন কাজের ভার দেন না, সে তাই পায় যা সে উপার্জন করে এবং তাই তার উপর বর্তায় যা সে করে। হে আমাদের পালনকর্তা, যদি আমরা ভুলে যাই কিংবা ভুল করি, তবে আমাদেরকে অপরাধী করো না। হে আমাদের পালনকর্তা! এবং আমাদের উপর এমন দায়িত্ব অর্পণ করো না, যেমন আমাদের পূর্ববর্তীদের উপর অর্পণ করেছ, হে আমাদের প্রভু! এবং আমাদের দ্বারা ঐ বোঝা বহন করাও না, যা বহন করার শক্তি আমাদের নাই। আমাদের পাপ মোচন কর। আমাদেরকে ক্ষমা কর এবং আমাদের প্রতি দয়া কর। তুমিই আমাদের প্রভু। সুতরাং কাফের সম্প্রদায়ের বিরুদ্ধে আমাদের জয়ী কর।",
      hi: "रसूल ईमान लाया उस चीज़ पर जो उसकी तरफ़ उसके रब की जानिब से नाज़िल की गई और मोमिन भी, सब ईमान लाए अल्लाह पर और उसके फ़रिश्तों पर और उसकी किताबों पर और उसके रसूलों पर, हम उसके रसूलों में से किसी में फ़र्क़ नहीं करते, और वो कहते हैं हमने सुना और इताअत की, ऐ हमारे रब तेरी मग़फ़िरत चाहते हैं और तेरी ही तरफ़ लौटना है। अल्लाह किसी जान को उसकी ताक़त से ज़्यादा तकलीफ़ नहीं देता, उसके लिए है जो उसने कमाया और उसके ऊपर है जो उसने बुराई कमाई, ऐ हमारे रब हमारी गिरफ़्त न कर अगर हम भूल जाएं या ख़ता करें, ऐ हमारे रब हम पर बोझ न डाल जैसा कि तूने डाला था हमसे पहले लोगों पर, ऐ हमारे रब हम पर वो बोझ न डाल जिसकी हमें ताक़त नहीं, और हमें माफ़ कर दे और हमें बख़्श दे और हम पर रहम कर, तू हमारा मौला है पस हमारी मदद कर काफ़िरों की क़ौम पर",
      id: "Rasul telah beriman kepada Al-Quran yang diturunkan kepadanya dari Tuhannya, demikian pula orang-orang yang beriman. Semuanya beriman kepada Allah, malaikat-malaikat-Nya, kitab-kitab-Nya dan rasul-rasul-Nya. (Mereka mengatakan): 'Kami tidak membeda-bedakan antara seseorangpun (dengan yang lain) dari rasul-rasul-Nya', dan mereka mengatakan: 'Kami dengar dan kami taat'. (Mereka berdoa): 'Ampunilah kami ya Tuhan kami dan kepada Engkaulah tempat kembali'. Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. Ia mendapat pahala (dari kebajikan) yang diusahakannya dan ia mendapat siksa (dari kejahatan) yang dikerjakannya. (Mereka berdoa): 'Ya Tuhan kami, janganlah Engkau hukum kami jika kami lupa atau kami tersalah. Ya Tuhan kami, janganlah Engkau bebankan kepada kami beban yang berat sebagaimana Engkau bebankan kepada orang-orang sebelum kami. Ya Tuhan kami, janganlah Engkau pikulkan kepada kami apa yang tak sanggup kami memikulnya. Beri ma'aflah kami; ampunilah kami; dan rahmatilah kami. Engkaulah Penolong kami, maka tolonglah kami terhadap kaum yang kafir.'"
    },
    transliteration: {
      en: "Full transliteration is very long - see individual verses",
      ur: "آمن الرسول بما انزل الیہ من ربہ والمومنون کل آمن باللہ وملائکتہ وکتبہ ورسلہ لا نفرق بین احد من رسلہ وقالوا سمعنا واطعنا غفرانک ربنا والیک المصیر۔ لا یکلف اللہ نفسا الا وسعہا لہا ما کسبت وعلیہا ما اکتسبت ربنا لا تواخذنا ان نسینا او اخطانا ربنا ولا تحمل علینا اصرا کما حملتہ علی الذین من قبلنا ربنا ولا تحملنا ما لا طاقۃ لنا بہ واعف عنا واغفر لنا وارحمنا انت مولانا فانصرنا علی القوم الکافرین",
      bn: "আমানার রাসূলু বিমা উনযিলা ইলাইহি মির রাব্বিহি ওয়াল মু'মিনূন...",
      hi: "आमनर रसूलु बिमा उनज़िला इलैहि मिर रब्বিही वल मुमिनून...",
      id: "Aamanar rasuulu bimaa unzila ilaihi mir rabbihi wal mu'minuun..."
    },
    benefits: {
      en: "The recitation of the last 2 verses of Surah Al-Baqara is sufficient for (the benefit of) the slave",
      ur: "سورۃ البقرۃ کی آخری 2 آیات کی تلاوت بندے کے لیے (رات میں) کافی ہو جاتی ہے",
      bn: "সূরা বাকারার শেষ ২ আয়াত তিলাওয়াত বান্দার জন্য (রাতে) যথেষ্ট",
      hi: "सूरह बक़रह की आख़िरी 2 आयात की तिलावत बन्दे के लिए (रात में) काफ़ी हो जाती है",
      id: "Membaca 2 ayat terakhir Surah Al-Baqarah sudah cukup bagi seorang hamba (di malam hari)"
    },
    repetitions: 1,
    category: "evening",
    order: 22,
    references: [
      { bookId: "bukhari", number: 4008 },
      { bookId: "muslim", number: 1878 }
    ]
  },
  {
    id: "surah_mulk_note",
    arabic: "سورة الملك",
    translations: {
      en: "Surah Al-Mulk (Chapter 67 - complete recitation)",
      ur: "سورۃ الملک (مکمل تلاوت)",
      bn: "সূরা মুলক (সম্পূর্ণ তিলাওয়াত)",
      hi: "सूरह मुल्क (मुकम्मल तिलावत)",
      id: "Surah Al-Mulk (bacaan lengkap)"
    },
    transliteration: {
      en: "Surah Al-Mulk",
      ur: "سورۃ الملک",
      bn: "সূরা মুলক",
      hi: "सूरह मुल्क",
      id: "Surah Al-Mulk"
    },
    benefits: {
      en: "Surah Al-Mulk will intercede for the person who recites it until he is forgiven. It will also protect from the punishment of the grave",
      ur: "سورۃ الملک تلاوت کرنے والے کی شفاعت کرے گی یہاں تک کہ اسے معاف کر دیا جائے۔ یہ سورت قبر میں بھی تمام آزمائش سے بچائے گی",
      bn: "সূরা মুলক পাঠকারীর জন্য সুপারিশ করবে যতক্ষণ না তাকে ক্ষমা করা হয়। এটি কবরের আযাব থেকেও রক্ষা করবে",
      hi: "सूरह मुल्क तिलावत करने वाले की सिफ़ारिश करेगी यहां तक कि उसे माफ़ कर दिया जाए। ये सूरत क़ब्र में भी तमाम आज़माइश से बचाएगी",
      id: "Surah Al-Mulk akan memberi syafaat bagi yang membacanya hingga ia diampuni. Surah ini juga akan melindungi dari siksa kubur"
    },
    repetitions: 1,
    category: "evening",
    order: 23,
    references: [
      { bookId: "abu_dawud", number: 1400 }
    ]
  }
];

export async function seedFirestore() {
  console.log(
    "🌱 Starting Firestore seeding with complete multilingual azkar data..."
  );

  try {
    const azkarCollection = collection(db, "azkar");

    for (const zikr of azkarData) {
      const { id, ...data } = zikr;
      await setDoc(doc(azkarCollection, id), data);
      console.log(`✅ Added: ${id}`);
    }

    console.log("🎉 Firestore seeding completed successfully!");
    console.log(`📊 Total azkar added: ${azkarData.length}`);
    console.log(
      "🌍 Languages supported: Arabic, English, Urdu, Bengali, Hindi, Indonesian"
    );
  } catch (error) {
    console.error("❌ Error seeding Firestore:", error);
    throw error;
  }
}
